---
# tasks file for core/ansible/roles/aws-cli
# Currently I just support for CentOS setup. For other OS environment feel free to contribute
# The post-setup is dedicated to EC2. For other cloud server type on GCP or Azure, feel free to contribute
- name: Install unzip on CentOS
  become: yes
  become_user: root
  yum:
    name:
      - unzip
    state: present
  tags:
    - cli
    - centos

- name: Download the awscli bundle.
  become: yes
  become_user: root
  get_url:
    url:  https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
    dest: /tmp/awscli-bundle.zip
  register: aws_cli_download_bundle
  tags:
    - cli

- name: Unarchive the aws installer
  become: yes
  become_user: root
  unarchive:
    src: /tmp/awscli-bundle.zip
    dest: /tmp
    copy: no
    creates: /tmp/awscli-bundle
  when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer
  tags:
    - cli

- name: Install aws-cli executable
  become: yes
  become_user: root
  ansible.builtin.shell: |
    /tmp/awscli-bundle/install -i {{ aws_cli_install_dir }} -b {{ aws_cli_bin }}
  args:
    executable: /bin/bash
    creates: "{{ aws_cli_bin }}"
  when: aws_cli_unarchive_installer.changed
  tags:
    - cli

- name: Set up AWS profile on EC2 using docker
  become: yes
  become_user: root
  tags:
    - ec2
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{ role_path }}/templates/ec2-aws-cred.j2"
      dest: "{{ aws_dir }}/credentials"
    - src: "{{ role_path }}/templates/ec2-aws-config.j2"
      dest: "{{ aws_dir }}/config" 
  