name: Code quality
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - master
  push:
    branches:
      - master

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install
        run: |
          npm ci
      - name: Check prettier
        run: |
          npm run format:check
      - name: Check commitlint
        uses: wagoid/commitlint-github-action@v4
        if: github.event_name == 'pull_request' && github.base_ref == 'master'